### ISSUE TITLE
Improve file type checking

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/ImageDePHI#129]
Currently we employ a combination of file suffix checking and metadata analysis to determine whether we can or cannot redact an image. We do this while building redaction plans for images, and throw exceptions when we come across files we cannot redact. This leads to defensive exception handling that is starting to get unwieldy.

Perhaps a better solution would be to check all of the files prior to redaction, and keep track of which files we can and can't redact.

We could use [magic numbers ](https://en.wikipedia.org/wiki/List_of_file_signatures) instead of file suffixes, in conjunction with checking for certain metadata tags/values to determing Aperio/Philips/ImageJ files.

**Comment by manthey** [comment]
If we are only handling tiff files, checking the first four bytes for any of four variations (more than in the linked article since it has to include the bigtiff variants) is sufficient. 

I'd advocate for the `python-magic` library, but I don't think it has a binary wheel, so we'd have to pull in libmagic ourselves, which is a pain in windows.

**Comment by naglepuff** [comment]
Closing this particular instance of this issue. We've started to check file signatures to differentiate between tiff and dicom images.
