### ISSUE TITLE
Reduce confusion at end of workflow

### ISSUE THREAD

**Issue by marySalvi** [DigitalSlideArchive/ImageDePHI#158]
Currently the UI ends abruptly after redaction. Improving this portion of the workflow would greatly reduce user confusion. ie. allowing further interaction and results information

**Comment by cooperlab** [comment]
As a user I would really like to see a report of the redaction outcome, indicating successes and errors. People running this tool are going to be responsible for any PHI leaks that occur, and this would provide reassurance that the tool ran successfully, and if there are any images they need to exclude due to failure (so they don't leak PHI).
